name = "reST"
grammar = "rst"
path_suffixes = ["rst"]
line_comments = [".. "]

brackets = [
    { start = "``", end = "``", close = true, newline = false, not_in = ["comment"] },
    { start = "`", end = "`", close = true, newline = false, not_in = ["comment"] },
    { start = "**", end = "**", close = true, newline = false, not_in = ["comment"] },
    { start = "*", end = "*", close = true, newline = false, not_in = ["comment"] },
    { start = "(", end = ")", close = true, newline = false },
    { start = "[", end = "]", close = true, newline = false },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment"] },
]

